### PR TITLE
WIP: Add support for D3 extensions

### PR DESCRIPTION
**Pull request by javierluraschi**
Adds support to include extensions with ease, say `d3-jetpack`, `rickshaw`, etc. Couple examples:

## Jetpack

```js
// !preview r2d3 data=c(0.3, 0.6, 0.8, 0.95, 0.40, 0.20), dependencies = d3_extension("d3-jetpack")

var { svg, margin, height, width } = d3.conventions({
  sel: svg,
  totalWidth: width,
  totalHeight: height,
  margin: { top: 60, bottom: 60 }
});

var barHeight = Math.ceil(height / data.length);

svg.selectAll('rect')
  .data(data)
  .enter().append('rect')
    .attr('width', function(d) { return d * width; })
    .attr('height', barHeight)
    .attr('y', function(d, i) { return i * barHeight; })
    .attr('fill', 'steelblue');
```

screen shot 2018-04-25 at 2 22 27 am

## Rickshaw

```js
// !preview r2d3 data = dplyr::transmute(Orange, x = age, y = circumference), container = "div", dependencies = d3_extension("rickshaw"), d3_version = 3, options = list(type = "bar")

var graph = new Rickshaw.Graph({
  element: div.node(),
  width: width,
  height: height,
  renderer: options.type,
  series: [{
    color: 'orange',
    data: data
  }]
});

graph.render();
```

screen shot 2018-04-25 at 2 23 03 am

### CODE REVIEW

**Comment by jjallaire** [comment]
This is a great idea! I would do it a bit differently though, let me take a shot at another PR.

**Comment by jjallaire** [comment]
Here is my thinking on using another approach:

1) We want these extensions to also be available as standard html dependency functions (as we do with the `html_dependency_d3()` function) and the custom mechanism with dynamic download defaults that.

2) It's simple enough to either include script files directly (as you show in the docs) or include proper html dependencies, I don't think we need to create yet another channel (the extensions.csv file) which we then have to reason about what to include, document, provide examples, etc.).

I'd favor one of 3 approaches here:

1) If we think that there are a set of very fundamental extensions (like jetpack), we could add an extensions argument to `html_dependency_d3()`, so something like this:

    ```r
    html_dependency_d3 <- function(version = c("5", "4", "3"), extensions = NULL) {

    }
    ```

Now the extensions become available to packages that want to use `html_dependency_d3()` directly (this will be common as it's the only sane way to create new htmlwidgets based on D3 v4+ without conflicting with existing widgets that use D3 v3).

We can then extend the `r2d3()` function to include an extensions parameter:

```r
r2d3 <- function(
  data,
  script,
  css = "auto",
  extensions = "jetpack",
  dependencies = NULL, 
  ...) {

}
```

Does this sound like a reasonable approach?

**Comment by jjallaire** [comment]
One thing that's important in our extensions implementation is that they be added as proper html-dependency objects (rather than just added to the list of scripts) as that will make them subject to de-duplication and latest version resolution.

Also important to note that the `dependencies` parameter which just includes a script is in general sketchy territory as that script will be include multiple times / not subject to standard de-duplication and latest version resolution.

**Comment by javierluraschi** [comment]
K, I'll move the dependencies to be included in the package rather than to be downloaded.

**Pull request closed without merging**
